root ::= equation ";"
equation ::= lhs LUID? " = " expr
lhs ::= "()" | lhs_item
lhs_item ::= ID | "_"
expr ::= id_expr binary_op id_expr | unary_op expr
id_expr ::= path_id | "last " NAME
path_id ::= ID ("::" ID)*
NAME ::= "'"ID
unary_op ::= " - " | " + " | " lnot " | " not " | " pre " 
binary_op ::= " + " | " - " | " * " | " / " | " mod " | " land " | " lor " | " lxor " | " lsl " | " lsr " | " = " | " <> " | " < " | " > " | " <= " | " >= " | " and " | " or " | " xor " | " -> " | " pre " | "@"
LUID ::= "$" ID
ID ::= WORD
WORD ::= LETTER ALPHANUMERIC*
ALPHANUMERIC ::= DIGIT10 | LETTER
DIGIT10 ::= [0-9]
LETTER ::= [a-zA-Z]